import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CountryProvider } from "@/context/CountryContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "naukrigulf",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  bbai-tooltip-injected="true">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="fixed top-0 left-0 h-[100vh] w-[100vw]">
          <video
            src="/video/bg.mp4"
            className="h-[100vh] w-[100vw] object-cover"
            muted
            playsInline
            autoPlay
            loop
          ></video>
        </div>
        <CountryProvider>{children}</CountryProvider>
      </body>
    </html>
  );
}
